# Generated by Django 6.0.3 on 2026-04-17 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_notification_options_booking_price_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhythm', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('pending', 'En traitement'), ('matched', 'Assigné'), ('cancelled', 'Annulé')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to='api.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(related_name='course_requests', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente de transmission'), ('transmitted', "Transmis à l'élève"), ('rejected', "Refusé par l'admin")], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='api.teacherprofile')),
                ('course_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='api.courserequest')),
            ],
            options={
                'unique_together': {('course_request', 'teacher')},
            },
        ),
    ]
