# Generated by Django 6.0.3 on 2026-05-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_teacherprofile_status_courserequest_courseinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinterest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de transmission'), ('transmitted', "Transmis à l'élève"), ('accepted', "Accepté par l'élève"), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
