# Generated by Django 6.0.3 on 2026-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='bac_diploma',
            field=models.FileField(blank=True, null=True, upload_to='teacher_docs/bac/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='civil_servant_certificate',
            field=models.FileField(blank=True, null=True, upload_to='teacher_docs/certificates/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='teacher_docs/identity/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_civil_servant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='last_diploma',
            field=models.FileField(blank=True, null=True, upload_to='teacher_docs/diplomas/'),
        ),
    ]
