# Generated by Django 6.0.3 on 2026-07-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_teacher_document_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_type',
            field=models.CharField(choices=[('fonctionnaire', "Fonctionnaire de l'État"), ('prive', 'Enseignant du secteur privé'), ('etudiant', 'Étudiant enseignant')], default='prive', max_length=20),
        ),
    ]
